// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAof5I6sFubERBmkTmge0F5l9kd_OuK5L0',
    appId: '1:989795674199:web:c70daaee677374104c1b12',
    messagingSenderId: '989795674199',
    projectId: 'emergency-d2250',
    authDomain: 'emergency-d2250.firebaseapp.com',
    storageBucket: 'emergency-d2250.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEcLV9Hc12s7gLaS-oItAI1WxPGNKDksk',
    appId: '1:989795674199:android:d576c394950c7d2a4c1b12',
    messagingSenderId: '989795674199',
    projectId: 'emergency-d2250',
    databaseURL: 'https://emergency-d2250-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emergency-d2250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01FND2ZsETMcjo4Z6YijCwUpa_R0Yei8',
    appId: '1:989795674199:ios:486b5b41e89894e44c1b12',
    messagingSenderId: '989795674199',
    projectId: 'emergency-d2250',
    databaseURL: 'https://emergency-d2250-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emergency-d2250.appspot.com',
    iosBundleId: 'com.example.emergencyapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA01FND2ZsETMcjo4Z6YijCwUpa_R0Yei8',
    appId: '1:989795674199:ios:486b5b41e89894e44c1b12',
    messagingSenderId: '989795674199',
    projectId: 'emergency-d2250',
    storageBucket: 'emergency-d2250.appspot.com',
    iosBundleId: 'com.example.emergencyapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAof5I6sFubERBmkTmge0F5l9kd_OuK5L0',
    appId: '1:989795674199:web:7ea2b2083fe42ccf4c1b12',
    messagingSenderId: '989795674199',
    projectId: 'emergency-d2250',
    authDomain: 'emergency-d2250.firebaseapp.com',
    storageBucket: 'emergency-d2250.appspot.com',
  );
}